parameters:
    # todo - find solution without a whole override
    ibexa.field_type.richtext.converter.input.xhtml5.resources: "%kernel.project_dir%/vendor/contextualcode/ezplatform-content-variables/src/bundle/Resources/richtext/stylesheets/xhtml5/edit/docbook.xsl"

    ibexa.field_type.richtext.validator.docbook.resources:
        - "%kernel.project_dir%/vendor/contextualcode/ezplatform-content-variables/src/bundle/Resources/richtext/schemas/docbook/ezpublish.rng"
        - "%ibexa.field_type.richtext.resources%/schemas/docbook/docbook.iso.sch.xsl"
