content_variables:
    resource: "@EzPlatformContentVariablesBundle/Controller/VariableController.php"
    prefix: /
    type: annotation

content_variables_collection:
    resource: "@EzPlatformContentVariablesBundle/Controller/CollectionController.php"
    prefix: /
    type: annotation

content_variables_rest_collection:
    resource: "@EzPlatformContentVariablesBundle/REST/Controller/Collection.php"
    prefix: '%ibexa.rest.path_prefix%'
    type: annotation
